/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Point;

/**
 *
 * @author UO279176
 */
public class ElegirHeroe extends javax.swing.JFrame {

    private Principal VPrincipal;
    
    private Personaje[] heroesPersonalizados = new Personaje [5];
    /**
     * Creates new form ElegirHeroe
     */
    public ElegirHeroe() {
        initComponents();
        
        DPersCustom = new PersonajeCustom();
        this.LPersonalizadoH.setModel(new javax.swing.DefaultListModel());
        
    }
    
    public ElegirHeroe(Principal VP)
    {
        this();
        
        this.VPrincipal = VP;
        paintHeroes = (DibujadoHeroes)PDibujarH;
        TareaC = new TareaCuadricula(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGHeroes = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        RBGuerrero = new javax.swing.JRadioButton();
        RBBrujo = new javax.swing.JRadioButton();
        RBAsesino = new javax.swing.JRadioButton();
        RBOgro = new javax.swing.JRadioButton();
        RBPersonalizadoH = new javax.swing.JRadioButton();
        PPersonalizados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LPersonalizadoH = new javax.swing.JList<>();
        BAgregarH = new javax.swing.JButton();
        BEliminarH = new javax.swing.JButton();
        PDibujarH = new DibujadoHeroes();
        jLabel4 = new javax.swing.JLabel();
        BBorrarH = new javax.swing.JButton();
        LEnemigo = new javax.swing.JLabel();
        LFatigaH = new javax.swing.JLabel();
        LProbCritH = new javax.swing.JLabel();
        LDefensaH = new javax.swing.JLabel();
        LAtaqueH = new javax.swing.JLabel();
        LVidaH = new javax.swing.JLabel();
        LNombreH = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PBCuadricula = new javax.swing.JProgressBar();
        TFCuadricula = new javax.swing.JTextField();
        CBCuadricula = new javax.swing.JComboBox<>();
        LCuadricula = new javax.swing.JLabel();
        BEjecutarCuadricula = new javax.swing.JButton();
        BPararCuadricula = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Elige tu héroe");

        BGHeroes.add(RBGuerrero);
        RBGuerrero.setSelected(true);
        RBGuerrero.setText("Guerrero");
        RBGuerrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBGuerreroActionPerformed(evt);
            }
        });

        BGHeroes.add(RBBrujo);
        RBBrujo.setText("Brujo");
        RBBrujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBBrujoActionPerformed(evt);
            }
        });

        BGHeroes.add(RBAsesino);
        RBAsesino.setText("Asesino");
        RBAsesino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBAsesinoActionPerformed(evt);
            }
        });

        BGHeroes.add(RBOgro);
        RBOgro.setText("Ogro");
        RBOgro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBOgroActionPerformed(evt);
            }
        });

        BGHeroes.add(RBPersonalizadoH);
        RBPersonalizadoH.setText("Personalizado");
        RBPersonalizadoH.setEnabled(false);
        RBPersonalizadoH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPersonalizadoHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBAsesino)
                    .addComponent(RBOgro)
                    .addComponent(RBPersonalizadoH)
                    .addComponent(RBGuerrero)
                    .addComponent(RBBrujo))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBGuerrero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBBrujo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBAsesino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBOgro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBPersonalizadoH)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Predefinidos", jPanel1);

        LPersonalizadoH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LPersonalizadoH.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                LPersonalizadoHValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(LPersonalizadoH);

        BAgregarH.setText("Agregar héroe");
        BAgregarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarHActionPerformed(evt);
            }
        });

        BEliminarH.setText("Eliminar héroe");
        BEliminarH.setEnabled(false);
        BEliminarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarHActionPerformed(evt);
            }
        });

        PDibujarH.setBackground(new java.awt.Color(255, 255, 255));
        PDibujarH.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PDibujarHMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout PDibujarHLayout = new javax.swing.GroupLayout(PDibujarH);
        PDibujarH.setLayout(PDibujarHLayout);
        PDibujarHLayout.setHorizontalGroup(
            PDibujarHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PDibujarHLayout.setVerticalGroup(
            PDibujarHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setText("¡Dibuja al héroe!");

        BBorrarH.setText("Borrar");
        BBorrarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PPersonalizadosLayout = new javax.swing.GroupLayout(PPersonalizados);
        PPersonalizados.setLayout(PPersonalizadosLayout);
        PPersonalizadosLayout.setHorizontalGroup(
            PPersonalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPersonalizadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PPersonalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BEliminarH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(BAgregarH, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGroup(PPersonalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PPersonalizadosLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44)
                        .addComponent(BBorrarH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PPersonalizadosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PDibujarH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PPersonalizadosLayout.setVerticalGroup(
            PPersonalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPersonalizadosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PPersonalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBorrarH)
                    .addComponent(jLabel4)
                    .addComponent(BAgregarH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PPersonalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PPersonalizadosLayout.createSequentialGroup()
                        .addComponent(BEliminarH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PPersonalizadosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(PDibujarH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Personalizados", PPersonalizados);

        LEnemigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LEnemigo.setText("Enemigo actual: Null");

        LFatigaH.setText("Fatiga inicial: 0");

        LProbCritH.setText("Prob. crítica: 0");

        LDefensaH.setText("Defensa: 0");

        LAtaqueH.setText("Ataque: 0");

        LVidaH.setText("Vida: 0");

        LNombreH.setText("Nombre: Null");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Estadísticas");

        TFCuadricula.setToolTipText("");
        TFCuadricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFCuadriculaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFCuadriculaKeyTyped(evt);
            }
        });

        CBCuadricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.005", "0.01", "0.05", "0.1", "0.5", "1.0" }));

        LCuadricula.setText("Número de puntos: 0");

        BEjecutarCuadricula.setText("Ejecutar");
        BEjecutarCuadricula.setEnabled(false);
        BEjecutarCuadricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEjecutarCuadriculaActionPerformed(evt);
            }
        });

        BPararCuadricula.setText("Parar");
        BPararCuadricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPararCuadriculaActionPerformed(evt);
            }
        });

        jLabel5.setText("Tiempo/Iteración");

        jLabel6.setText("Tamaño cuadrícula");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Cuadrícula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(TFCuadricula, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(CBCuadricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BEjecutarCuadricula)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(BPararCuadricula))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LAtaqueH)
                                    .addComponent(LDefensaH)
                                    .addComponent(LProbCritH)
                                    .addComponent(LFatigaH)
                                    .addComponent(LNombreH)
                                    .addComponent(LVidaH)
                                    .addComponent(jLabel2)
                                    .addComponent(LCuadricula))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LEnemigo, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PBCuadricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PBCuadricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(LNombreH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LVidaH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LAtaqueH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LDefensaH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LProbCritH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LFatigaH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BEjecutarCuadricula)
                                    .addComponent(BPararCuadricula)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LCuadricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFCuadricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CBCuadricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addComponent(jTabbedPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LEnemigo)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAgregarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarHActionPerformed
        // TODO add your handling code here:
        if (DPersCustom.showDialog())
        {
            javax.swing.DefaultListModel Model=(javax.swing.DefaultListModel)this.LPersonalizadoH.getModel();
            
            int ind = Model.size();
            heroesPersonalizados[ind] = new Personaje(DPersCustom.getNombreD(), DPersCustom.getVidaD(),
                                DPersCustom.getAtaqueD(), DPersCustom.getDefensaD(),
                                DPersCustom.getProbCritD(), DPersCustom.getFatigaID());
            
            Model.addElement(heroesPersonalizados[ind].getNombre());
            VPrincipal.setHeroe(heroesPersonalizados[ind]);
            VPrincipal.seCambioPersonaje();
            this.LPersonalizadoH.setSelectedIndex(ind);
            RBPersonalizadoH.setSelected(true);
            
            BAgregarH.setEnabled(Model.size() < 5);
            RBPersonalizadoH.setEnabled(true);
        }
    }//GEN-LAST:event_BAgregarHActionPerformed

    private void BEliminarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarHActionPerformed
        // TODO add your handling code here:
        javax.swing.DefaultListModel Model=(javax.swing.DefaultListModel)this.LPersonalizadoH.getModel();
        int indice = LPersonalizadoH.getSelectedIndex();
        Model.removeElementAt(indice);
        
        if (Model.size() == indice)
        {
            this.LPersonalizadoH.setSelectedIndex(indice - 1);
            
            if (Model.size() == 0)
            {
                VPrincipal.setHeroe("Mago supremo (Pers. oculto)", 999, 99, 99, 99, 0);
            }
            else VPrincipal.setHeroe(heroesPersonalizados[indice-1]);
        }
        else
        {
            this.LPersonalizadoH.setSelectedIndex(indice);
            VPrincipal.setHeroe(heroesPersonalizados[indice]);
        }
        VPrincipal.seCambioPersonaje();
        RBPersonalizadoH.setSelected(true);
    }//GEN-LAST:event_BEliminarHActionPerformed

    private void LPersonalizadoHValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_LPersonalizadoHValueChanged
        // TODO add your handling code here:
        this.BEliminarH.setEnabled(!this.LPersonalizadoH.isSelectionEmpty());
        RBPersonalizadoH.setEnabled(!this.LPersonalizadoH.isSelectionEmpty());
    }//GEN-LAST:event_LPersonalizadoHValueChanged

    private void RBGuerreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBGuerreroActionPerformed
        // TODO add your handling code here:
        VPrincipal.setHeroe("Guerrero", 168, 35, 14, 10, 5);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBGuerreroActionPerformed

    private void RBBrujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBBrujoActionPerformed
        // TODO add your handling code here:
        VPrincipal.setHeroe("Brujo", 203, 20, 9, 35, 8);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBBrujoActionPerformed

    private void RBAsesinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBAsesinoActionPerformed
        // TODO add your handling code here:
        VPrincipal.setHeroe("Asesino", 152, 46, 10, 15, 15);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBAsesinoActionPerformed

    private void RBOgroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBOgroActionPerformed
        // TODO add your handling code here:
        VPrincipal.setHeroe("Ogro", 240, 28, 28, 8, 10);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBOgroActionPerformed

    private void RBPersonalizadoHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPersonalizadoHActionPerformed
        // TODO add your handling code here:
        javax.swing.DefaultListModel Model=(javax.swing.DefaultListModel)this.LPersonalizadoH.getModel();
        int indice = LPersonalizadoH.getSelectedIndex();
        VPrincipal.setHeroe(heroesPersonalizados[indice]);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBPersonalizadoHActionPerformed

    private void PDibujarHMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PDibujarHMouseDragged
        // TODO add your handling code here:
        paintHeroes.insertaPunto(new Point(evt.getPoint()));
        paintHeroes.repaint();
    }//GEN-LAST:event_PDibujarHMouseDragged

    private void BBorrarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarHActionPerformed
        // TODO add your handling code here:
        paintHeroes.borra();
        paintHeroes.repaint();
    }//GEN-LAST:event_BBorrarHActionPerformed

    private void TFCuadriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFCuadriculaKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) evt.consume();
    }//GEN-LAST:event_TFCuadriculaKeyTyped

    private void TFCuadriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFCuadriculaKeyReleased
        // TODO add your handling code here:
        if (TFCuadricula.getText().length() > 1)
            if (Integer.parseInt(TFCuadricula.getText()) > Math.min(paintHeroes.getHeight(), paintHeroes.getWidth())/2) TFCuadricula.setText(""+Math.min(paintHeroes.getHeight(), paintHeroes.getWidth())/2);
        BEjecutarCuadricula.setEnabled(!(TFCuadricula.getText() == ""));
    }//GEN-LAST:event_TFCuadriculaKeyReleased

    private void BPararCuadriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPararCuadriculaActionPerformed
        // TODO add your handling code here:
        TareaC.setStop(); // Parar la tarea

        BPararCuadricula.setEnabled(false);   
    }//GEN-LAST:event_BPararCuadriculaActionPerformed

    private void BEjecutarCuadriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEjecutarCuadriculaActionPerformed
        // TODO add your handling code here:
        
        // Parámetros de la tarea
        int tamCuadri = Integer.parseInt(TFCuadricula.getText());
        TareaC.setTamCuadricula(tamCuadri); 
        float SegsIter = Float.parseFloat(CBCuadricula.getSelectedItem().toString());
        TareaC.setSegsInte(SegsIter);
        int anc = PDibujarH.getWidth();
        TareaC.setAncho(anc);
        int alt = PDibujarH.getHeight();
        TareaC.setAlto(alt);
        
        // Crear un hilo que lance la tarea
        HiloC=new Thread(){public void run(){ElegirHeroe.TareaC.Run();}};        
        HiloC.start(); // Lanzar el hilo (ejecutará Run)
        
        // Permitir que desde el interfaz se pueda pausar y parar
        BPararCuadricula.setEnabled(true);
        BEjecutarCuadricula.setEnabled(false);    
        TFCuadricula.setEnabled(false);
        
    }//GEN-LAST:event_BEjecutarCuadriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirHeroe().setVisible(true);
            }
        });
    }
    
    private PersonajeCustom DPersCustom;
    protected DibujadoHeroes paintHeroes;
    
    static private TareaCuadricula TareaC; // Tarea 
    private Thread HiloC;                  // Hilo de la tarea

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgregarH;
    private javax.swing.JButton BBorrarH;
    javax.swing.JButton BEjecutarCuadricula;
    private javax.swing.JButton BEliminarH;
    private javax.swing.ButtonGroup BGHeroes;
    javax.swing.JButton BPararCuadricula;
    private javax.swing.JComboBox<String> CBCuadricula;
    javax.swing.JLabel LAtaqueH;
    javax.swing.JLabel LCuadricula;
    javax.swing.JLabel LDefensaH;
    javax.swing.JLabel LEnemigo;
    javax.swing.JLabel LFatigaH;
    javax.swing.JLabel LNombreH;
    private javax.swing.JList<String> LPersonalizadoH;
    javax.swing.JLabel LProbCritH;
    javax.swing.JLabel LVidaH;
    javax.swing.JProgressBar PBCuadricula;
    private javax.swing.JPanel PDibujarH;
    private javax.swing.JPanel PPersonalizados;
    private javax.swing.JRadioButton RBAsesino;
    private javax.swing.JRadioButton RBBrujo;
    private javax.swing.JRadioButton RBGuerrero;
    private javax.swing.JRadioButton RBOgro;
    private javax.swing.JRadioButton RBPersonalizadoH;
    javax.swing.JTextField TFCuadricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
