/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Point;

/**
 *
 * @author UO279176
 */
public class ElegirEnemigo extends javax.swing.JFrame {

    private Principal VPrincipal;
    
    /**
     * Creates new form ElegirHeroe
     */
    public ElegirEnemigo() {
        initComponents();
        
    }
    
    public ElegirEnemigo(Principal VP)
    {
        this();
        
        this.VPrincipal = VP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGEnemigos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        LHeroe = new javax.swing.JLabel();
        LFatigaE = new javax.swing.JLabel();
        LProbCritE = new javax.swing.JLabel();
        LDefensaE = new javax.swing.JLabel();
        LAtaqueE = new javax.swing.JLabel();
        LVidaE = new javax.swing.JLabel();
        LNombreE = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        RBZombie = new javax.swing.JRadioButton();
        RBEsqueleto = new javax.swing.JRadioButton();
        RBEspectro = new javax.swing.JRadioButton();
        RBSlime = new javax.swing.JRadioButton();
        RBCreeper = new javax.swing.JRadioButton();
        RBMurcielagoSolar = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        RBSectarioLunatico = new javax.swing.JRadioButton();
        RBEmperatrizDeLaLuz = new javax.swing.JRadioButton();
        RBGolem = new javax.swing.JRadioButton();
        RBElDestructor = new javax.swing.JRadioButton();
        RBProvidenciaDiosaSagrada = new javax.swing.JRadioButton();
        RBDevoradorDeMundosSupremo = new javax.swing.JRadioButton();

        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Elige el enemigo");

        LHeroe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LHeroe.setText("Héroe actual: Null");

        LFatigaE.setText("Fatiga inicial: 0");

        LProbCritE.setText("Prob. crítica: 0");

        LDefensaE.setText("Defensa: 0");

        LAtaqueE.setText("Ataque: 0");

        LVidaE.setText("Vida: 0");

        LNombreE.setText("Nombre: Null");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Estadísticas");

        BGEnemigos.add(RBZombie);
        RBZombie.setSelected(true);
        RBZombie.setText("Zombie");
        RBZombie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBZombieActionPerformed(evt);
            }
        });

        BGEnemigos.add(RBEsqueleto);
        RBEsqueleto.setText("Esqueleto");
        RBEsqueleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBEsqueletoActionPerformed(evt);
            }
        });

        BGEnemigos.add(RBEspectro);
        RBEspectro.setText("Espectro");
        RBEspectro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBEspectroActionPerformed(evt);
            }
        });

        BGEnemigos.add(RBSlime);
        RBSlime.setText("Slime");
        RBSlime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSlimeActionPerformed(evt);
            }
        });

        BGEnemigos.add(RBCreeper);
        RBCreeper.setText("Creeper");
        RBCreeper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBCreeperActionPerformed(evt);
            }
        });

        BGEnemigos.add(RBMurcielagoSolar);
        RBMurcielagoSolar.setText("Murciélago solar");
        RBMurcielagoSolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMurcielagoSolarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBZombie)
                    .addComponent(RBEsqueleto)
                    .addComponent(RBSlime)
                    .addComponent(RBEspectro)
                    .addComponent(RBMurcielagoSolar)
                    .addComponent(RBCreeper))
                .addGap(99, 99, 99))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBZombie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBEsqueleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBEspectro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBSlime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBMurcielagoSolar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBCreeper)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Monstruos", jPanel2);

        BGEnemigos.add(RBSectarioLunatico);
        RBSectarioLunatico.setText("Sectario lunático");
        RBSectarioLunatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSectarioLunaticoActionPerformed(evt);
            }
        });

        BGEnemigos.add(RBEmperatrizDeLaLuz);
        RBEmperatrizDeLaLuz.setText("Emperatriz de la luz");
        RBEmperatrizDeLaLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBEmperatrizDeLaLuzActionPerformed(evt);
            }
        });

        BGEnemigos.add(RBGolem);
        RBGolem.setText("Gólem");
        RBGolem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBGolemActionPerformed(evt);
            }
        });

        BGEnemigos.add(RBElDestructor);
        RBElDestructor.setText("El Destructor");
        RBElDestructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBElDestructorActionPerformed(evt);
            }
        });

        BGEnemigos.add(RBProvidenciaDiosaSagrada);
        RBProvidenciaDiosaSagrada.setText("Providencia, la Diosa Sagrada");
        RBProvidenciaDiosaSagrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBProvidenciaDiosaSagradaActionPerformed(evt);
            }
        });

        BGEnemigos.add(RBDevoradorDeMundosSupremo);
        RBDevoradorDeMundosSupremo.setText("Devorador de mundos supremo");
        RBDevoradorDeMundosSupremo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBDevoradorDeMundosSupremoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBEmperatrizDeLaLuz)
                    .addComponent(RBSectarioLunatico)
                    .addComponent(RBGolem)
                    .addComponent(RBElDestructor)
                    .addComponent(RBProvidenciaDiosaSagrada)
                    .addComponent(RBDevoradorDeMundosSupremo))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBSectarioLunatico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBEmperatrizDeLaLuz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBGolem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBElDestructor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBProvidenciaDiosaSagrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBDevoradorDeMundosSupremo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Jefes", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(LHeroe)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LAtaqueE)
                            .addComponent(LDefensaE)
                            .addComponent(LProbCritE)
                            .addComponent(LFatigaE)
                            .addComponent(LNombreE)
                            .addComponent(LVidaE)
                            .addComponent(jLabel2))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(LNombreE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LVidaE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LAtaqueE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LDefensaE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LProbCritE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LFatigaE))
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LHeroe)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBSectarioLunaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSectarioLunaticoActionPerformed
        // TODO add your handling code here:
        setFalseIAAvanzada();
        VPrincipal.setEnemigo("Sectario lunático", 500, 35, 10, 10, 10);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBSectarioLunaticoActionPerformed

    private void RBEspectroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBEspectroActionPerformed
        // TODO add your handling code here:
        setFalseIAAvanzada();
        VPrincipal.setEnemigo("Espectro", 200, 32, 25, 10, 7);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBEspectroActionPerformed

    private void RBEsqueletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBEsqueletoActionPerformed
        // TODO add your handling code here:
        setFalseIAAvanzada();
        VPrincipal.setEnemigo("Esqueleto", 150, 30, 0, 5, 1);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBEsqueletoActionPerformed

    private void RBMurcielagoSolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMurcielagoSolarActionPerformed
        // TODO add your handling code here:
        setFalseIAAvanzada();
        VPrincipal.setEnemigo("Murciélago solar", 200, 35, 10, 3, 20);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBMurcielagoSolarActionPerformed

    private void RBSlimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSlimeActionPerformed
        // TODO add your handling code here:
        setFalseIAAvanzada();
        VPrincipal.setEnemigo("Slime", 400, 16, 5, 2, 9);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBSlimeActionPerformed

    private void RBEmperatrizDeLaLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBEmperatrizDeLaLuzActionPerformed
        // TODO add your handling code here:
        setFalseIAAvanzada();
        VPrincipal.setEnemigo("Emperatriz de la luz", 600, 32, 15, 14, 9);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBEmperatrizDeLaLuzActionPerformed

    private void RBZombieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBZombieActionPerformed
        // TODO add your handling code here:
        setFalseIAAvanzada();
        VPrincipal.setEnemigo("Zombie", 125, 20, 25, 0, 0);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBZombieActionPerformed

    private void RBCreeperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBCreeperActionPerformed
        // TODO add your handling code here:
        setFalseIAAvanzada();
        VPrincipal.setEnemigo("Creeper", 114, 80, 0, 1, 30);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBCreeperActionPerformed

    private void RBGolemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBGolemActionPerformed
        // TODO add your handling code here:
        setFalseIAAvanzada();
        VPrincipal.setEnemigo("Gólem", 700, 32, 25, 0, 24);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBGolemActionPerformed

    private void RBElDestructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBElDestructorActionPerformed
        // TODO add your handling code here:
        setFalseIAAvanzada();
        VPrincipal.setEnemigo("El Destructor", 420, 51, 5, 2, 15);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBElDestructorActionPerformed

    private void RBProvidenciaDiosaSagradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBProvidenciaDiosaSagradaActionPerformed
        // TODO add your handling code here:
        setFalseIAAvanzada();
        VPrincipal.setEnemigo("Providencia, la Diosa Sagrada", 750, 38, 40, 25, 23);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBProvidenciaDiosaSagradaActionPerformed

    private void RBDevoradorDeMundosSupremoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBDevoradorDeMundosSupremoActionPerformed
        // TODO add your handling code here:
        setFalseIAAvanzada();
        VPrincipal.setEnemigo("Devorador de mundos supremo", 1150, 65, 45, 33, 16);
        VPrincipal.seCambioPersonaje();
    }//GEN-LAST:event_RBDevoradorDeMundosSupremoActionPerformed

    public void setFalseIAAvanzada()
    {
        VPrincipal.CBIAAvanzada.setSelected(false);
        VPrincipal.CBMIIAAvanzada.setSelected(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirEnemigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGEnemigos;
    javax.swing.JLabel LAtaqueE;
    javax.swing.JLabel LDefensaE;
    javax.swing.JLabel LFatigaE;
    javax.swing.JLabel LHeroe;
    javax.swing.JLabel LNombreE;
    javax.swing.JLabel LProbCritE;
    javax.swing.JLabel LVidaE;
    private javax.swing.JRadioButton RBCreeper;
    private javax.swing.JRadioButton RBDevoradorDeMundosSupremo;
    private javax.swing.JRadioButton RBElDestructor;
    private javax.swing.JRadioButton RBEmperatrizDeLaLuz;
    private javax.swing.JRadioButton RBEspectro;
    private javax.swing.JRadioButton RBEsqueleto;
    private javax.swing.JRadioButton RBGolem;
    private javax.swing.JRadioButton RBMurcielagoSolar;
    private javax.swing.JRadioButton RBProvidenciaDiosaSagrada;
    private javax.swing.JRadioButton RBSectarioLunatico;
    private javax.swing.JRadioButton RBSlime;
    private javax.swing.JRadioButton RBZombie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
